### PR TITLE
Feature/support all mongo connection options

### PR DESCRIPTION
**Pull request by ctaschereau**

### CODE REVIEW

**Comment by okv** [comment]
Hey there. I'll try to take a look at this on the weekend.

**Comment by okv** [comment]
Great job in general :+1: But there are some suggestions:
* Add test for `_createCollection` with `connection options`, [_createCollection/withUserAndPassword.js](https://github.com/2do2go/rate-limit-mongo/blob/master/test/mongoStore/_createCollection/withUserAndPassword.js) could be as used as a base for such test
* Clarify in the docs that default connection options are `useUnifiedTopology: true`, `useNewUrlParser: true`

**Comment by davidtrepanier** [comment]
@okv I clarified the doc as mentioned and added tests with the connection options. I updated a few libraries to make sure everything is up to date. I also thought we might want to change the minor version, making this version 2.3.0

**Comment by davidtrepanier** [comment]
@okv I clarified the doc as mentioned and added the tests with `connectionOptions`. I thought we might also want to change the minor version, so this would be version `2.3.0`.

**Comment by okv** [comment]
@davidtrepanier, I've just made another PR #23 with small changes which is based on this PR. It's merged and published to npm as rate-limit-mongo@2.3.0. Thanks a lot for your contribution.

**Comment by okv** [comment]
Closing this since all commits already in master...

**Pull request closed without merging**
